
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: RABBIT_MQ
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.docker.rabbitmq
    networks:
      - urban-flow-network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  monitoring-db:
    image: postgres:15
    env_file:
      - .env.docker
    ports:
      - "5005:5432"
    volumes:
      - monitoring-db:/var/lib/postgresql/data
    networks:
      - urban-flow-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_logs" ]
      interval: 10s
      timeout: 5s
      retries: 5

  monitoring-service:
    build: .
    env_file:
      - .env.docker
    ports:
      - "4005:4005"
    depends_on:
      monitoring-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - urban-flow-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - urban-flow-network
    restart: unless-stopped


volumes:
  monitoring-db:

networks:
  urban-flow-network:
    driver: bridge
